--- #YAML:1.0
name: Graphics-ColorNames-GrayScale
version: 1.00
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: grayscale colors for Graphics::ColorNames
license: perl
requires:
  Graphics::ColorNames: 1.01
  perl: 5.6.0
build_requires:
  Test: 0
provides:
  Graphics::ColorNames::GrayScale:
    file: lib/Graphics/ColorNames/GrayScale.pm
    version: 1.00
generated_by: Module::Build version 0.25_02
